---
title: "Publishing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Publishing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

There are several different ways to share to share your custom dashboard online, including posit connect cloud and shiny server. For smaller organizations, I recommend [posit connect cloud](https://connect.posit.cloud/) because it is straightforward to use and the free tier includes 20 hours of active use per month.

## Uploading to Posit Connect Cloud

1.  Log in or make an account on [posit connect cloud](https://connect.posit.cloud/). 

2. Paste `rsconnect::connectCloudUser()` in the console window and hit `ENTER`. This will open posit connect cloud in a browser window; follow the prompts to authorize access. 

3.  Run `data-raw/08_launch.R`. If prompted with a message that WQdashboard is not installed, select option `1`. 
4.  Posit connect cloud will host the dashboard as a standalone website. The home page for posit connect cloud will provide a link to each active website. 

## Embedding

WQdashboard can be embedded in any other website with an [iframe](https://www.w3schools.com/tags/tag_iframe.asp). Simply copy the code below and replace "LINK" with the link to your dashboard. The height, width, and title can be adjusted as needed.

```{html, eval = FALSE}
<iframe src="LINK" title="Water Quality Dashboard" width="100%" height = "800"></iframe>
```

WQdashboard will load whenever the page it is embedded on is opened. If you are concerned about using too many active hours, embed WQdashboard on its own page instead of the homepage.
