---
output: pdf_document
params:
  df_report: NULL
  report_title: NULL
  always_allow_html: true
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
---

```{r setup, echo = FALSE, message = FALSE}
# Import packages
library(kableExtra)
```

```{r table, echo = FALSE, warnings = FALSE}

# Drop extra rows
df_report <- params$df_report
row_count <- nrow(df_report)

# Create kable
kable(df_report, "latex", longtable = T, booktabs = T, 
      caption = params$report_title) %>%
  kable_styling(latex_options = c("repeat_header")) %>%
  # # Set max column width
  # column_spec(1:4, width = "8em") %>%
  # Style header
  row_spec(0, bold = T, background = "#EEEEEE") %>%
  # Color code final column
  column_spec(5, background=case_when(
    df_report$score_str == 'Excellent' ~  '#afccec',
    df_report$score_str %in% c('Good', "Meets Criteria") ~ '#cbe4e7',
    df_report$score_str == 'Fair' ~ '#ffffe0', 
    df_report$score_str %in% c('Poor', "Does Not Meet Criteria") ~ '#f9cfb4',
    TRUE ~ '#FFFFFF')) %>%
  # Add line after each row
  row_spec(1:row_count, hline_after=T)

```
