---
format: 
  html:
    output-file: About.html
    minimal: true
engine: knitr
brand: false
---

# About this Site

WQdashboard is an open-source dashboard template that can be used to display water quality data using interactive maps, report cards, and graphs. It is designed for water quality organizations who want to share their data with the public. This site is a **demo** containing ten years of data collected by the [Salt Ponds Coalition](https://saltpondscoalition.org/).

If you would like to learn more about WQdashboard, please read the [documentation](https://nbep.github.io/WQdashboard/articles/wqdashboard.html) or download the code from [GitHub](https://github.com/NBEP/WQdashboard/).

## How are scores calculated?

Scores are calculated using state or site specific thresholds. The scoring system is designed to provide a rough approximation of the health of the watershed, but should not be mistaken for official guidance or classifications. For up to date, official information on which waterbodies are healthy or impaired, go to [How's My Waterway?](https://mywaterway.epa.gov/)
